# Generated by Django 4.2 on 2026-03-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GFlipkart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("food_grains", "Food Grains"),
                    ("pulses", "Pulses"),
                    ("fruits", "Fruits"),
                    ("vegetables", "Vegetables"),
                    ("cash_crops", "Cash Crops"),
                ],
                default="food_grains",
                max_length=50,
            ),
        ),
    ]
